version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: restapi/sync-api
    ports:
      - 80:80
    volumes:
      - .:/srv/app
#      - /srv/vendor
  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - mysql-data:/var/lib/mysql
      - ./custom.cnf:/etc/mysql/conf.d/custom.cnf
volumes:
  mysql-data:
